/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { InMemoryTabularStorage } from "@workglow/storage";
import { describe } from "vitest";
import { runGenericTabularRepositorySubscriptionTests } from "./genericTabularRepositorySubscriptionTests";
import {
  AllTypesPrimaryKeyNames,
  AllTypesSchema,
  AutoIncrementPrimaryKeyNames,
  AutoIncrementSchema,
  CompoundPrimaryKeyNames,
  CompoundSchema,
  runAutoGeneratedKeyTests,
  runGenericTabularRepositoryTests,
  SearchPrimaryKeyNames,
  SearchSchema,
  UuidPrimaryKeyNames,
  UuidSchema,
} from "./genericTabularRepositoryTests";

describe("InMemoryTabularStorage", () => {
  runGenericTabularRepositoryTests(
    async () =>
      new InMemoryTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
        CompoundSchema,
        CompoundPrimaryKeyNames
      ),
    async () =>
      new InMemoryTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
        SearchSchema,
        SearchPrimaryKeyNames,
        ["category", ["category", "subcategory"], ["subcategory", "category"], "value"]
      ),
    async () =>
      new InMemoryTabularStorage<typeof AllTypesSchema, typeof AllTypesPrimaryKeyNames>(
        AllTypesSchema,
        AllTypesPrimaryKeyNames
      )
  );

  runGenericTabularRepositorySubscriptionTests(
    async () =>
      new InMemoryTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
        CompoundSchema,
        CompoundPrimaryKeyNames
      ),
    { usesPolling: false }
  );

  runAutoGeneratedKeyTests(
    async () =>
      new InMemoryTabularStorage<typeof AutoIncrementSchema, typeof AutoIncrementPrimaryKeyNames>(
        AutoIncrementSchema,
        AutoIncrementPrimaryKeyNames
      ),
    async () =>
      new InMemoryTabularStorage<typeof UuidSchema, typeof UuidPrimaryKeyNames>(
        UuidSchema,
        UuidPrimaryKeyNames
      )
  );
});
