/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { SqliteTabularStorage } from "@workglow/storage";
import { setLogger, uuid4 } from "@workglow/util";
import { describe } from "vitest";
import { getTestingLogger } from "../../binding/TestingLogger";
import {
  AllTypesPrimaryKeyNames,
  AllTypesSchema,
  AutoIncrementPrimaryKeyNames,
  AutoIncrementSchema,
  CompoundPrimaryKeyNames,
  CompoundSchema,
  runAutoGeneratedKeyTests,
  runGenericTabularStorageTests,
  SearchPrimaryKeyNames,
  SearchSchema,
  UuidPrimaryKeyNames,
  UuidSchema,
} from "./genericTabularStorageTests";

describe("SqliteTabularStorage", () => {
  let logger = getTestingLogger();
  setLogger(logger);
  runGenericTabularStorageTests(
    async () =>
      new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        CompoundSchema,
        CompoundPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        SearchSchema,
        SearchPrimaryKeyNames,
        ["category", ["category", "subcategory"], ["subcategory", "category"], "value"]
      ),
    async () => {
      const repo = new SqliteTabularStorage<typeof AllTypesSchema, typeof AllTypesPrimaryKeyNames>(
        ":memory:",
        `all_types_test_${uuid4().replace(/-/g, "_")}`,
        AllTypesSchema,
        AllTypesPrimaryKeyNames
      );
      await repo.setupDatabase();
      return repo;
    }
  );

  runAutoGeneratedKeyTests(
    async () =>
      new SqliteTabularStorage<typeof AutoIncrementSchema, typeof AutoIncrementPrimaryKeyNames>(
        ":memory:",
        `autoinc_test_${uuid4().replace(/-/g, "_")}`,
        AutoIncrementSchema,
        AutoIncrementPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof UuidSchema, typeof UuidPrimaryKeyNames>(
        ":memory:",
        `uuid_test_${uuid4().replace(/-/g, "_")}`,
        UuidSchema,
        UuidPrimaryKeyNames
      )
  );
});
