/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * Run with: RUN_STORAGE_TESTS=1 bun test storage-tabular
 */

import { SqliteTabularStorage } from "@workglow/storage";
import { uuid4 } from "@workglow/util";
import { describe } from "vitest";
import {
  AllTypesPrimaryKeyNames,
  AllTypesSchema,
  AutoIncrementPrimaryKeyNames,
  AutoIncrementSchema,
  CompoundPrimaryKeyNames,
  CompoundSchema,
  runAutoGeneratedKeyTests,
  runGenericTabularRepositoryTests,
  SearchPrimaryKeyNames,
  SearchSchema,
  UuidPrimaryKeyNames,
  UuidSchema,
} from "./genericTabularRepositoryTests";

const RUN_STORAGE_TESTS = !!process.env.RUN_STORAGE_TESTS || !!process.env.RUN_ALL_TESTS;

describe.skipIf(!RUN_STORAGE_TESTS)("SqliteTabularStorage", () => {
  runGenericTabularRepositoryTests(
    async () =>
      new SqliteTabularStorage<typeof CompoundSchema, typeof CompoundPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        CompoundSchema,
        CompoundPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof SearchSchema, typeof SearchPrimaryKeyNames>(
        ":memory:",
        `sql_test_${uuid4().replace(/-/g, "_")}`,
        SearchSchema,
        SearchPrimaryKeyNames,
        ["category", ["category", "subcategory"], ["subcategory", "category"], "value"]
      ),
    async () => {
      const repo = new SqliteTabularStorage<typeof AllTypesSchema, typeof AllTypesPrimaryKeyNames>(
        ":memory:",
        `all_types_test_${uuid4().replace(/-/g, "_")}`,
        AllTypesSchema,
        AllTypesPrimaryKeyNames
      );
      await repo.setupDatabase();
      return repo;
    }
  );

  runAutoGeneratedKeyTests(
    async () =>
      new SqliteTabularStorage<typeof AutoIncrementSchema, typeof AutoIncrementPrimaryKeyNames>(
        ":memory:",
        `autoinc_test_${uuid4().replace(/-/g, "_")}`,
        AutoIncrementSchema,
        AutoIncrementPrimaryKeyNames
      ),
    async () =>
      new SqliteTabularStorage<typeof UuidSchema, typeof UuidPrimaryKeyNames>(
        ":memory:",
        `uuid_test_${uuid4().replace(/-/g, "_")}`,
        UuidSchema,
        UuidPrimaryKeyNames
      )
  );
});
