/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import type { ImageBinary, ImageDataSupport } from "@workglow/util/media";
import { Image, MediaRawImage } from "@workglow/util/media";
// Side-effect import: registers the Node raster codec so `Image.getPixels()`
// and `Image.getDataUri()` have a codec to dispatch to in this test.
import "@workglow/tasks";
import { describe, expect, test } from "vitest";

function pixels(width: number, height: number, channels: 1 | 3 | 4, fill: number[]): ImageBinary {
  const data = new Uint8ClampedArray(width * height * channels);
  for (let i = 0; i < width * height; i++) {
    for (let c = 0; c < channels; c++) {
      data[i * channels + c] = fill[c % fill.length]!;
    }
  }
  return { data, width, height, channels };
}

/** Minimal valid 1×1 RGB PNG data URI (generated by sharp). */
const PNG_1X1_DATA_URI =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVR4nGPgEpEDAABoAD1UCKP3AAAAAElFTkSuQmCC";

describe("Image", () => {
  describe("toJSON / fromJSON round-trip", () => {
    test("pixel-form image serializes with a plain number array (no indexed-object)", () => {
      const p = pixels(2, 2, 3, [10, 20, 30]);
      const img = Image.fromPixels(p);
      const json = img.toJSON();
      expect(typeof json).toBe("object");
      const obj = json as { data: unknown; width: number; height: number; channels: number };
      expect(Array.isArray(obj.data)).toBe(true);
      expect(obj.width).toBe(2);
      expect(obj.height).toBe(2);
      expect(obj.channels).toBe(3);
    });

    test("data-URI image serializes as the raw data URI string", () => {
      const img = Image.fromDataUri(PNG_1X1_DATA_URI);
      expect(img.toJSON()).toBe(PNG_1X1_DATA_URI);
    });

    test("fromJSON accepts the legacy indexed-object `data` shape", () => {
      const p = pixels(1, 1, 3, [1, 2, 3]);
      const indexedObj = {
        data: { 0: 1, 1: 2, 2: 3 },
        width: 1,
        height: 1,
        channels: 3,
      };
      const rebuilt = Image.fromJSON(indexedObj);
      // getPixels is sync-safe here because source is already `pixels`.
      expect(rebuilt.kind).toBe("pixels");
      expect(rebuilt.width).toBe(p.width);
      expect(rebuilt.channels).toBe(3);
    });

    test("JSON.stringify + Image.fromJSON round-trips byte-equal pixels", async () => {
      const p = pixels(3, 2, 4, [11, 22, 33, 44]);
      const img = Image.fromPixels(p);
      const roundTripped = Image.fromJSON(JSON.parse(JSON.stringify(img)));
      const decoded = await roundTripped.getPixels();
      expect(decoded.width).toBe(p.width);
      expect(decoded.height).toBe(p.height);
      expect(decoded.channels).toBe(p.channels);
      expect(Array.from(decoded.data)).toEqual(Array.from(p.data));
    });

    test("fromJSON accepts a raw data-URI string", async () => {
      const img = Image.fromJSON(PNG_1X1_DATA_URI);
      expect(img.kind).toBe("dataUri");
      expect(img.mimeType).toBe("image/png");
    });
  });

  describe("Image.is / Image.from", () => {
    test("Image.is only matches class instances", () => {
      const img = Image.fromPixels(pixels(1, 1, 3, [0, 0, 0]));
      expect(Image.is(img)).toBe(true);
      expect(Image.is(PNG_1X1_DATA_URI)).toBe(false);
      expect(Image.is({ data: [], width: 1, height: 1, channels: 3 })).toBe(false);
      expect(Image.is(null)).toBe(false);
    });

    test("Image.from normalizes strings, ImageBinary shapes, and Image instances", () => {
      expect(Image.from(PNG_1X1_DATA_URI).kind).toBe("dataUri");
      expect(Image.from(pixels(1, 1, 4, [1, 2, 3, 4])).kind).toBe("pixels");
      const i = Image.fromPixels(pixels(1, 1, 3, [0, 0, 0]));
      expect(Image.from(i)).toBe(i);
    });

    test("Image.from rejects unsupported shapes", () => {
      expect(() => Image.from(42)).toThrow(/unsupported/i);
      expect(() => Image.from({ width: 1 })).toThrow(/unsupported/i);
    });
  });

  describe("decode / encode", () => {
    test("getPixels on a data URI returns pixels via the registered codec", async () => {
      const img = Image.fromDataUri(PNG_1X1_DATA_URI);
      const p = await img.getPixels();
      expect(p.width).toBe(1);
      expect(p.height).toBe(1);
      expect(p.channels === 3 || p.channels === 4).toBe(true);
      expect(p.data.length).toBe(p.channels);
    });

    test("getDataUri on a pixel-form image round-trips through the codec", async () => {
      const p = pixels(2, 2, 3, [100, 150, 200]);
      const img = Image.fromPixels(p);
      const dataUri = await img.getDataUri("image/png");
      expect(dataUri.startsWith("data:image/png;base64,")).toBe(true);
      const reDecoded = await Image.fromDataUri(dataUri).getPixels();
      // PNG is lossless so the first pixel's RGB channels must survive.
      expect(reDecoded.data[0]).toBe(100);
      expect(reDecoded.data[1]).toBe(150);
      expect(reDecoded.data[2]).toBe(200);
    });
  });

  describe("toFirstSupported (parity with convertImageDataToUseableForm)", () => {
    test("pass-through when the source matches a supported form", async () => {
      const p = pixels(1, 1, 3, [0, 0, 0]);
      const img = Image.fromPixels(p);
      const supports: ImageDataSupport[] = ["Blob", "ImageBinary"];
      const out = await img.toFirstSupported(supports);
      expect(out).toBe(p);
    });

    test("data URI → Blob when Blob is requested (matches legacy node behavior)", async () => {
      const img = Image.fromDataUri(PNG_1X1_DATA_URI);
      const out = await img.toFirstSupported(["Blob"]);
      expect(out).toBeInstanceOf(Blob);
    });

    test("pixel form → MediaRawImage when RawImage is requested", async () => {
      const p = pixels(1, 1, 3, [10, 20, 30]);
      const img = Image.fromPixels(p);
      const out = await img.toFirstSupported(["RawImage"]);
      expect(out).toBeInstanceOf(MediaRawImage);
      const raw = out as MediaRawImage;
      expect(raw.width).toBe(1);
      expect(raw.height).toBe(1);
      expect(raw.channels).toBe(3);
      expect(Array.from(raw.data)).toEqual([10, 20, 30]);
    });

    test("throws when no requested form is producible on this platform", async () => {
      const img = Image.fromPixels(pixels(1, 1, 3, [0, 0, 0]));
      // `ImageBitmap` is browser-only; on node it's unavailable, so the
      // request must fall through to a clear error.
      await expect(img.toFirstSupported(["ImageBitmap"])).rejects.toThrow(/toFirstSupported/);
    });
  });
});
