name: Build & Test
permissions:
  contents: read
  pull-requests: write

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}
  cancel-in-progress: true

env:
  CI: "true"
  DO_NOT_TRACK: "1"
  TURBO_TELEMETRY_DISABLED: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      - run: bun run build
      - run: bun run test
      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
